const data = [
  {
    id: 1,
    name: "Classic Margherita Pizza",
    image: "https://cdn.dummyjson.com/recipe-images/1.webp",
    tags: ["Pizza", "Italian"],
    rating: 4.6,
    reviewCount: 98,
    mealType: "Main Dish",
    price: 24,
    like: false,
    special: true,
  },
  {
    id: 2,
    name: "Vegetarian Stir-Fry",
    image: "https://cdn.dummyjson.com/recipe-images/2.webp",
    tags: ["Vegetarian", "Stir-fry", "Asian"],
    rating: 4.7,
    reviewCount: 26,
    mealType: "Main Dish",
    price: 18,
    like: false,
    special: false,
  },
  {
    id: 3,
    name: "Chocolate Chip Cookies",
    image: "https://cdn.dummyjson.com/recipe-images/3.webp",
    tags: ["Cookies", "Dessert", "Baking"],
    rating: 4.9,
    reviewCount: 13,
    mealType: "Dessert",
    price: 10,
    like: false,
    special: false,
  },
  {
    id: 4,
    name: "Chicken Alfredo Pasta",
    image: "https://cdn.dummyjson.com/recipe-images/4.webp",
    tags: ["Pasta", "Chicken"],
    rating: 4.9,
    reviewCount: 82,
    mealType: "Main Dish",
    price: 22,
    like: false,
    special: true,
  },
  {
    id: 5,
    name: "Mango Salsa Chicken",
    image: "https://cdn.dummyjson.com/recipe-images/5.webp",
    tags: ["Chicken", "Salsa"],
    rating: 4.9,
    reviewCount: 63,
    mealType: "Main Dish",
    price: 21,
    like: false,
    special: false,
  },
  {
    id: 6,
    name: "Quinoa Salad with Avocado",
    image: "https://cdn.dummyjson.com/recipe-images/6.webp",
    tags: ["Salad", "Quinoa"],
    rating: 4.4,
    reviewCount: 59,
    mealType: "Breakfast",
    price: 15,
    like: false,
    special: false,
  },
  {
    id: 7,
    name: "Tomato Basil Bruschetta",
    image: "https://cdn.dummyjson.com/recipe-images/7.webp",
    tags: ["Bruschetta", "Italian"],
    rating: 4.7,
    reviewCount: 95,
    mealType: "Breakfast",
    price: 13,
    like: false,
  },
  {
    id: 8,
    name: "Beef and Broccoli Stir-Fry",
    image: "https://cdn.dummyjson.com/recipe-images/8.webp",
    tags: ["Beef", "Stir-fry", "Asian"],
    rating: 4.7,
    reviewCount: 58,
    mealType: "Main Dish",
    price: 23,
    like: false,
    special: true,
  },
  {
    id: 11,
    name: "Chicken Biryani",
    image: "https://cdn.dummyjson.com/recipe-images/11.webp",
    tags: ["Biryani", "Chicken", "Indian"],
    rating: 5,
    reviewCount: 32,
    mealType: "Main Dish",
    price: 27,
    like: false,
    special: false,
  },
  {
    id: 16,
    name: "Japanese Ramen Soup",
    image: "https://cdn.dummyjson.com/recipe-images/16.webp",
    tags: ["Ramen", "Japanese", "Soup"],
    rating: 4.9,
    reviewCount: 38,
    mealType: "Main Dish",
    price: 25,
    like: false,
    special: true,
  },
  {
    id: 18,
    name: "Korean Bibimbap",
    image: "https://cdn.dummyjson.com/recipe-images/18.webp",
    tags: ["Bibimbap", "Korean", "Rice"],
    rating: 4.9,
    reviewCount: 56,
    mealType: "Main Dish",
    price: 26,
    like: false,
    special: true,
  },
  {
    id: 22,
    name: "Mango Lassi",
    image: "https://cdn.dummyjson.com/recipe-images/22.webp",
    tags: ["Lassi", "Mango"],
    rating: 4.7,
    reviewCount: 15,
    mealType: "Drinks",
    price: 8,
    like: false,
    special: false,
  },
  {
    id: 23,
    name: "Italian Tiramisu",
    image: "https://cdn.dummyjson.com/recipe-images/23.webp",
    tags: ["Tiramisu", "Italian"],
    rating: 4.6,
    reviewCount: 10,
    mealType: "Dessert",
    price: 12,
    like: false,
    special: true,
  },
  {
    id: 30,
    name: "Brazilian Caipirinha",
    image: "https://cdn.dummyjson.com/recipe-images/30.webp",
    tags: ["Caipirinha", "Brazilian", "Cocktail"],
    rating: 4.4,
    reviewCount: 55,
    mealType: "Drinks",
    price: 9,
    like: false,
    special: false,
  },
];

export default data;
